//! Published schemas (US-018 AC3).
//!
//! The JSON Schema is derived from the Rust protocol types themselves, so what
//! is published cannot describe a shape serde does not read. The TypeScript is
//! emitted from that same document rather than from a second description of the
//! types, for the same reason. Both are deterministic: every map is walked in
//! sorted key order and the method tables are walked in declaration order, so
//! two runs on one commit produce byte-identical files.
//!
//! The TypeScript emitter is a small compiler over a schema shape it does not
//! control. When it meets a node it cannot name it REFUSES rather than writing
//! `unknown`: an external client typed against `unknown` has lost the contract
//! silently, which is worse than a build that stops and names the node.

use std::collections::BTreeMap;

use serde_json::{Map, Value};

use crate::protocol::{
    CLIENT_METHODS, MethodSchema, PROTOCOL_VERSION, SERVER_NOTIFICATIONS, SERVER_REQUESTS,
    protocol_schemas,
};

/// File names of the published artifacts.
pub const JSON_SCHEMA_FILE: &str = "protocol.schema.json";
pub const TYPESCRIPT_FILE: &str = "protocol.d.ts";

/// Nodes of the published schema the emitter could not name.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error(
    "the TypeScript emitter cannot name {} schema node(s): {}",
    .nodes.len(),
    .nodes.join(", ")
)]
pub struct Degraded {
    pub nodes: Vec<String>,
}

/// The whole surface as one JSON Schema document.
pub fn json_schema_document() -> Value {
    let (requests, notifications, server_requests, definitions) = protocol_schemas();
    let mut root = Map::new();
    root.insert(
        "$schema".into(),
        Value::String("https://json-schema.org/draft/2020-12/schema".into()),
    );
    root.insert(
        "title".into(),
        Value::String("Pyxis app-server protocol".into()),
    );
    root.insert("protocolVersion".into(), Value::from(PROTOCOL_VERSION));
    root.insert("methods".into(), entries(&requests));
    root.insert("notifications".into(), entries(&notifications));
    root.insert("serverRequests".into(), entries(&server_requests));
    root.insert("$defs".into(), sorted(definitions));
    Value::Object(root)
}

fn entries(schemas: &[MethodSchema]) -> Value {
    Value::Array(
        schemas
            .iter()
            .map(|entry| {
                let mut map = Map::new();
                map.insert("method".into(), Value::String(entry.method.into()));
                map.insert("params".into(), entry.params.clone());
                if let Some(result) = &entry.result {
                    map.insert("result".into(), result.clone());
                }
                Value::Object(map)
            })
            .collect(),
    )
}

/// Rewrites every object with its keys in sorted order, recursively. A map
/// whose iteration order depends on a feature flag of a transitive dependency
/// would make the published file non-reproducible.
fn sorted(value: Value) -> Value {
    match value {
        Value::Object(map) => {
            let ordered: BTreeMap<String, Value> = map.into_iter().collect();
            Value::Object(
                ordered
                    .into_iter()
                    .map(|(key, value)| (key, sorted(value)))
                    .collect(),
            )
        }
        Value::Array(items) => Value::Array(items.into_iter().map(sorted).collect()),
        other => other,
    }
}

/// TypeScript declarations for the same surface.
pub fn typescript() -> Result<String, Degraded> {
    let document = json_schema_document();
    let mut emitter = Emitter::default();
    let mut out = String::new();
    out.push_str(
        "// Generated by `pyxis app-server --emit-schemas`. Do not edit.\n\
         // Source of truth: crates/agent-app-server/src/protocol.rs\n\n",
    );
    out.push_str(&format!(
        "export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n\n"
    ));

    let empty = Map::new();
    let defs = document
        .get("$defs")
        .and_then(Value::as_object)
        .unwrap_or(&empty);
    for (name, schema) in defs {
        if let Some(doc) = schema.get("description").and_then(Value::as_str) {
            out.push_str(&comment(doc, ""));
        }
        let rendered = emitter.ts_type(schema, 0, name);
        out.push_str(&format!("export type {name} = {rendered};\n\n"));
    }

    out.push_str(&emitter.table("ClientRequests", &document, "methods", true));
    out.push_str(&emitter.table("ServerNotifications", &document, "notifications", false));
    out.push_str(&emitter.table("ServerRequests", &document, "serverRequests", true));

    out.push_str("export type ClientMethod = ");
    out.push_str(&union_of(CLIENT_METHODS));
    out.push_str(";\n\nexport type ServerNotificationMethod = ");
    out.push_str(&union_of(SERVER_NOTIFICATIONS));
    out.push_str(";\n\nexport type ServerRequestMethod = ");
    out.push_str(&union_of(SERVER_REQUESTS));
    out.push_str(";\n");

    emitter.finish(out)
}

fn union_of(names: &[&str]) -> String {
    names
        .iter()
        .map(|name| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join(" | ")
}

fn comment(text: &str, indent: &str) -> String {
    let mut out = format!("{indent}/**\n");
    for line in text.lines() {
        out.push_str(&format!("{indent} * {line}\n"));
    }
    out.push_str(&format!("{indent} */\n"));
    out
}

/// Schema keywords that constrain nothing. A node carrying only these is the
/// free shape `{}` with documentation attached, which is what a documented
/// `serde_json::Value` derives to, and it means `unknown` on purpose.
const ANNOTATION_KEYWORDS: &[&str] = &[
    "$comment",
    "default",
    "deprecated",
    "description",
    "examples",
    "format",
    "readOnly",
    "title",
    "writeOnly",
];

fn is_free_shape(node: &Map<String, Value>) -> bool {
    node.keys()
        .all(|key| ANNOTATION_KEYWORDS.contains(&key.as_str()))
}

fn literal(value: &Value) -> String {
    match value {
        Value::String(text) => format!("\"{text}\""),
        Value::Null => "null".into(),
        other => other.to_string(),
    }
}

/// Renders JSON Schema nodes as TypeScript, remembering every node it had to
/// give up on so the caller can refuse to publish the result.
#[derive(Default)]
struct Emitter {
    degraded: Vec<String>,
}

impl Emitter {
    fn finish(self, rendered: String) -> Result<String, Degraded> {
        if self.degraded.is_empty() {
            Ok(rendered)
        } else {
            Err(Degraded {
                nodes: self.degraded,
            })
        }
    }

    /// A node the emitter cannot name. `unknown` is still what gets written, so
    /// the failure carries a whole document to look at rather than a fragment.
    fn give_up(&mut self, path: &str) -> String {
        self.degraded.push(path.to_string());
        "unknown".into()
    }

    fn table(&mut self, name: &str, document: &Value, key: &str, with_result: bool) -> String {
        let mut out = format!("export interface {name} {{\n");
        for entry in document
            .get(key)
            .and_then(Value::as_array)
            .map(Vec::as_slice)
            .unwrap_or_default()
        {
            let method = entry
                .get("method")
                .and_then(Value::as_str)
                .unwrap_or_default();
            let params = match entry.get("params") {
                Some(params) => self.ts_type(params, 1, &format!("{method}.params")),
                None => self.give_up(&format!("{method}.params")),
            };
            if with_result {
                let result = match entry.get("result") {
                    Some(result) => self.ts_type(result, 1, &format!("{method}.result")),
                    None => self.give_up(&format!("{method}.result")),
                };
                out.push_str(&format!(
                    "  \"{method}\": {{ params: {params}; result: {result} }};\n"
                ));
            } else {
                out.push_str(&format!("  \"{method}\": {{ params: {params} }};\n"));
            }
        }
        out.push_str("}\n\n");
        out
    }

    /// One JSON Schema node as a TypeScript type.
    fn ts_type(&mut self, schema: &Value, depth: usize, path: &str) -> String {
        match schema {
            // `true` and `{}` both mean "anything": a free shape is a contract,
            // not a node the emitter failed to read.
            Value::Bool(true) => return "unknown".into(),
            Value::Bool(false) => return "never".into(),
            _ => {}
        }
        let Some(node) = schema.as_object() else {
            return self.give_up(path);
        };
        if let Some(reference) = node.get("$ref").and_then(Value::as_str) {
            return match reference.rsplit('/').next() {
                Some(name) if !name.is_empty() => name.to_string(),
                _ => self.give_up(path),
            };
        }
        if let Some(constant) = node.get("const") {
            return literal(constant);
        }
        if let Some(values) = node.get("enum").and_then(Value::as_array) {
            return values.iter().map(literal).collect::<Vec<_>>().join(" | ");
        }
        for key in ["oneOf", "anyOf"] {
            if let Some(variants) = node.get(key).and_then(Value::as_array) {
                return variants
                    .iter()
                    .enumerate()
                    .map(|(index, variant)| {
                        self.ts_type(variant, depth, &format!("{path}.{key}[{index}]"))
                    })
                    .collect::<Vec<_>>()
                    .join(" | ");
            }
        }
        if let Some(parts) = node.get("allOf").and_then(Value::as_array) {
            let mut rendered: Vec<String> = parts
                .iter()
                .enumerate()
                .map(|(index, part)| self.ts_type(part, depth, &format!("{path}.allOf[{index}]")))
                .filter(|part| part != "unknown")
                .collect();
            // A `#[serde(flatten)]` produces the local properties NEXT TO the
            // `allOf`, so both halves are intersected.
            if node.contains_key("properties") {
                rendered.push(self.object(node, depth, path));
            }
            return match rendered.len() {
                0 => self.give_up(path),
                _ => rendered.join(" & "),
            };
        }
        match node.get("type") {
            Some(Value::String(kind)) => self.scalar(kind, node, depth, path),
            // A nullable field is `["string", "null"]` in the derived schema.
            Some(Value::Array(kinds)) => kinds
                .iter()
                .filter_map(Value::as_str)
                .map(|kind| self.scalar(kind, node, depth, path))
                .collect::<Vec<_>>()
                .join(" | "),
            _ if node.contains_key("properties") => self.object(node, depth, path),
            _ if is_free_shape(node) => "unknown".into(),
            _ => self.give_up(path),
        }
    }

    fn scalar(
        &mut self,
        kind: &str,
        node: &Map<String, Value>,
        depth: usize,
        path: &str,
    ) -> String {
        match kind {
            "string" => "string".into(),
            "integer" | "number" => "number".into(),
            "boolean" => "boolean".into(),
            "null" => "null".into(),
            "array" => {
                let items = match node.get("items") {
                    Some(items) => self.ts_type(items, depth, &format!("{path}[]")),
                    // An array with no declared item type is a free list, the
                    // array counterpart of `{}`.
                    None => "unknown".into(),
                };
                if items.contains(' ') {
                    format!("({items})[]")
                } else {
                    format!("{items}[]")
                }
            }
            "object" => self.object(node, depth, path),
            _ => self.give_up(path),
        }
    }

    fn object(&mut self, node: &Map<String, Value>, depth: usize, path: &str) -> String {
        let empty = Map::new();
        let properties: BTreeMap<&String, &Value> = node
            .get("properties")
            .and_then(Value::as_object)
            .unwrap_or(&empty)
            .iter()
            .collect();
        if properties.is_empty() {
            // An object with a free shape: `serde_json::Value` lands here.
            return "Record<string, unknown>".into();
        }
        let required: Vec<&str> = node
            .get("required")
            .and_then(Value::as_array)
            .map(|items| items.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        let indent = "  ".repeat(depth + 1);
        let closing = "  ".repeat(depth);
        let mut out = String::from("{\n");
        for (name, schema) in properties {
            if let Some(doc) = schema.get("description").and_then(Value::as_str) {
                out.push_str(&comment(doc, &indent));
            }
            let optional = if required.contains(&name.as_str()) {
                ""
            } else {
                "?"
            };
            let rendered = self.ts_type(schema, depth + 1, &format!("{path}.{name}"));
            out.push_str(&format!("{indent}{name}{optional}: {rendered};\n"));
        }
        out.push_str(&format!("{closing}}}"));
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(json_schema_document(), json_schema_document());
        assert_eq!(typescript(), typescript());
    }

    /// Every node of the published surface has a name. A schemars release that
    /// starts emitting a shape this emitter cannot read fails HERE, instead of
    /// shipping `unknown` into a client's type declarations.
    #[test]
    fn no_node_of_the_published_surface_degrades() {
        typescript().expect("every node is nameable");
    }

    #[test]
    fn an_unreadable_node_is_named_rather_than_written_as_unknown() {
        let mut emitter = Emitter::default();
        assert_eq!(
            emitter.ts_type(&Value::from(7), 0, "Broken.field"),
            "unknown"
        );
        assert_eq!(
            emitter.finish(String::new()).expect_err("degraded").nodes,
            vec!["Broken.field".to_string()]
        );
    }

    /// A `serde_json::Value` derives to a node with no constraint at all, with
    /// or without the doc comment of the field that holds it. Both are the free
    /// shape, not a node the emitter failed to read.
    #[test]
    fn a_free_shape_is_unknown_without_being_a_failure() {
        let mut emitter = Emitter::default();
        for node in [
            Value::Bool(true),
            serde_json::json!({}),
            serde_json::json!({"description": "the tool input, verbatim"}),
        ] {
            assert_eq!(emitter.ts_type(&node, 0, "Free.field"), "unknown");
        }
        assert!(emitter.finish(String::new()).is_ok());
    }

    /// AC3: every exposed method and notification is in the published document.
    /// The tables the dispatcher uses ARE the tables the schema is built from,
    /// so this asserts the property rather than a copy of it.
    #[test]
    fn the_document_covers_every_exposed_name() {
        let document = json_schema_document();
        let names = |key: &str| -> Vec<String> {
            document
                .get(key)
                .and_then(Value::as_array)
                .map(|entries| {
                    entries
                        .iter()
                        .filter_map(|entry| entry.get("method").and_then(Value::as_str))
                        .map(str::to_string)
                        .collect()
                })
                .unwrap_or_default()
        };
        assert_eq!(names("methods"), CLIENT_METHODS.to_vec());
        assert_eq!(names("notifications"), SERVER_NOTIFICATIONS.to_vec());
        assert_eq!(names("serverRequests"), SERVER_REQUESTS.to_vec());
        // A method entry declares both halves of its contract.
        for entry in document
            .get("methods")
            .and_then(Value::as_array)
            .expect("methods")
        {
            assert!(entry.get("params").is_some());
            assert!(entry.get("result").is_some());
        }
    }

    #[test]
    fn the_typescript_declares_every_method_and_its_types() {
        let ts = typescript().expect("nameable");
        for method in CLIENT_METHODS {
            assert!(ts.contains(&format!("\"{method}\":")), "missing {method}");
        }
        for notification in SERVER_NOTIFICATIONS {
            assert!(
                ts.contains(&format!("\"{notification}\":")),
                "missing {notification}"
            );
        }
        assert!(ts.contains("export type ThreadItem ="), "{ts}");
        assert!(ts.contains("export const PROTOCOL_VERSION = 1;"));
        // The flattened correlation is inlined by the derivation: its four
        // identifiers must be readable on the request that carries them.
        let approval = ts
            .split("export type CommandExecutionApprovalParams =")
            .nth(1)
            .and_then(|rest| rest.split("};").next())
            .expect("the approval request is declared");
        for field in ["threadId", "turnId", "itemId", "callId"] {
            assert!(approval.contains(field), "{field} missing from {approval}");
        }
    }
}
