//! Published schemas (US-018 AC3).
//!
//! The JSON Schema is derived from the Rust protocol types themselves, so what
//! is published cannot describe a shape serde does not read. The TypeScript is
//! emitted from that same document rather than from a second description of the
//! types, for the same reason. Both are deterministic: every map is walked in
//! sorted key order and the method tables are walked in declaration order, so
//! two runs on one commit produce byte-identical files.

use std::collections::BTreeMap;

use serde_json::{Map, Value};

use crate::protocol::{
    CLIENT_METHODS, MethodSchema, PROTOCOL_VERSION, SERVER_NOTIFICATIONS, SERVER_REQUESTS,
    protocol_schemas,
};

/// File names of the published artifacts.
pub const JSON_SCHEMA_FILE: &str = "protocol.schema.json";
pub const TYPESCRIPT_FILE: &str = "protocol.d.ts";

/// The whole surface as one JSON Schema document.
pub fn json_schema_document() -> Value {
    let (requests, notifications, server_requests, definitions) = protocol_schemas();
    let mut root = Map::new();
    root.insert(
        "$schema".into(),
        Value::String("https://json-schema.org/draft/2020-12/schema".into()),
    );
    root.insert(
        "title".into(),
        Value::String("Pyxis app-server protocol".into()),
    );
    root.insert("protocolVersion".into(), Value::from(PROTOCOL_VERSION));
    root.insert("methods".into(), entries(&requests));
    root.insert("notifications".into(), entries(&notifications));
    root.insert("serverRequests".into(), entries(&server_requests));
    root.insert("$defs".into(), sorted(definitions));
    Value::Object(root)
}

fn entries(schemas: &[MethodSchema]) -> Value {
    Value::Array(
        schemas
            .iter()
            .map(|entry| {
                let mut map = Map::new();
                map.insert("method".into(), Value::String(entry.method.into()));
                map.insert("params".into(), entry.params.clone());
                if let Some(result) = &entry.result {
                    map.insert("result".into(), result.clone());
                }
                Value::Object(map)
            })
            .collect(),
    )
}

/// Rewrites every object with its keys in sorted order, recursively. A map
/// whose iteration order depends on a feature flag of a transitive dependency
/// would make the published file non-reproducible.
fn sorted(value: Value) -> Value {
    match value {
        Value::Object(map) => {
            let ordered: BTreeMap<String, Value> = map.into_iter().collect();
            Value::Object(
                ordered
                    .into_iter()
                    .map(|(key, value)| (key, sorted(value)))
                    .collect(),
            )
        }
        Value::Array(items) => Value::Array(items.into_iter().map(sorted).collect()),
        other => other,
    }
}

/// TypeScript declarations for the same surface.
pub fn typescript() -> String {
    let document = json_schema_document();
    let mut out = String::new();
    out.push_str(
        "// Generated by `pyxis app-server --emit-schemas`. Do not edit.\n\
         // Source of truth: crates/agent-app-server/src/protocol.rs\n\n",
    );
    out.push_str(&format!(
        "export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n\n"
    ));

    let empty = Map::new();
    let defs = document
        .get("$defs")
        .and_then(Value::as_object)
        .unwrap_or(&empty);
    for (name, schema) in defs {
        if let Some(doc) = schema.get("description").and_then(Value::as_str) {
            out.push_str(&comment(doc, ""));
        }
        out.push_str(&format!("export type {name} = {};\n\n", ts_type(schema, 0)));
    }

    out.push_str(&table("ClientRequests", &document, "methods", true));
    out.push_str(&table(
        "ServerNotifications",
        &document,
        "notifications",
        false,
    ));
    out.push_str(&table("ServerRequests", &document, "serverRequests", true));

    out.push_str("export type ClientMethod = ");
    out.push_str(&union_of(CLIENT_METHODS));
    out.push_str(";\n\nexport type ServerNotificationMethod = ");
    out.push_str(&union_of(SERVER_NOTIFICATIONS));
    out.push_str(";\n\nexport type ServerRequestMethod = ");
    out.push_str(&union_of(SERVER_REQUESTS));
    out.push_str(";\n");
    out
}

fn union_of(names: &[&str]) -> String {
    names
        .iter()
        .map(|name| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join(" | ")
}

fn table(name: &str, document: &Value, key: &str, with_result: bool) -> String {
    let mut out = format!("export interface {name} {{\n");
    for entry in document
        .get(key)
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or_default()
    {
        let method = entry
            .get("method")
            .and_then(Value::as_str)
            .unwrap_or_default();
        let params = entry
            .get("params")
            .map(|p| ts_type(p, 1))
            .unwrap_or_else(|| "unknown".into());
        if with_result {
            let result = entry
                .get("result")
                .map(|r| ts_type(r, 1))
                .unwrap_or_else(|| "unknown".into());
            out.push_str(&format!(
                "  \"{method}\": {{ params: {params}; result: {result} }};\n"
            ));
        } else {
            out.push_str(&format!("  \"{method}\": {{ params: {params} }};\n"));
        }
    }
    out.push_str("}\n\n");
    out
}

fn comment(text: &str, indent: &str) -> String {
    let mut out = format!("{indent}/**\n");
    for line in text.lines() {
        out.push_str(&format!("{indent} * {line}\n"));
    }
    out.push_str(&format!("{indent} */\n"));
    out
}

/// One JSON Schema node as a TypeScript type.
fn ts_type(schema: &Value, depth: usize) -> String {
    match schema {
        // `true` and `{}` both mean "anything".
        Value::Bool(true) => return "unknown".into(),
        Value::Bool(false) => return "never".into(),
        _ => {}
    }
    let Some(node) = schema.as_object() else {
        return "unknown".into();
    };
    if let Some(reference) = node.get("$ref").and_then(Value::as_str) {
        return reference
            .rsplit('/')
            .next()
            .unwrap_or("unknown")
            .to_string();
    }
    if let Some(constant) = node.get("const") {
        return literal(constant);
    }
    if let Some(values) = node.get("enum").and_then(Value::as_array) {
        return values.iter().map(literal).collect::<Vec<_>>().join(" | ");
    }
    for key in ["oneOf", "anyOf"] {
        if let Some(variants) = node.get(key).and_then(Value::as_array) {
            return variants
                .iter()
                .map(|variant| ts_type(variant, depth))
                .collect::<Vec<_>>()
                .join(" | ");
        }
    }
    if let Some(parts) = node.get("allOf").and_then(Value::as_array) {
        let mut rendered: Vec<String> = parts
            .iter()
            .map(|part| ts_type(part, depth))
            .filter(|part| part != "unknown")
            .collect();
        // A `#[serde(flatten)]` produces the local properties NEXT TO the
        // `allOf`, so both halves are intersected.
        if node.contains_key("properties") {
            rendered.push(object(node, depth));
        }
        return match rendered.len() {
            0 => "unknown".into(),
            _ => rendered.join(" & "),
        };
    }
    match node.get("type") {
        Some(Value::String(kind)) => scalar(kind, node, depth),
        // A nullable field is `["string", "null"]` in the derived schema.
        Some(Value::Array(kinds)) => kinds
            .iter()
            .filter_map(Value::as_str)
            .map(|kind| scalar(kind, node, depth))
            .collect::<Vec<_>>()
            .join(" | "),
        _ if node.contains_key("properties") => object(node, depth),
        _ => "unknown".into(),
    }
}

fn scalar(kind: &str, node: &Map<String, Value>, depth: usize) -> String {
    match kind {
        "string" => "string".into(),
        "integer" | "number" => "number".into(),
        "boolean" => "boolean".into(),
        "null" => "null".into(),
        "array" => {
            let items = node
                .get("items")
                .map(|items| ts_type(items, depth))
                .unwrap_or_else(|| "unknown".into());
            if items.contains(' ') {
                format!("({items})[]")
            } else {
                format!("{items}[]")
            }
        }
        "object" => object(node, depth),
        _ => "unknown".into(),
    }
}

fn object(node: &Map<String, Value>, depth: usize) -> String {
    let empty = Map::new();
    let properties: BTreeMap<&String, &Value> = node
        .get("properties")
        .and_then(Value::as_object)
        .unwrap_or(&empty)
        .iter()
        .collect();
    if properties.is_empty() {
        // An object with a free shape: `serde_json::Value` lands here.
        return "Record<string, unknown>".into();
    }
    let required: Vec<&str> = node
        .get("required")
        .and_then(Value::as_array)
        .map(|items| items.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let indent = "  ".repeat(depth + 1);
    let closing = "  ".repeat(depth);
    let mut out = String::from("{\n");
    for (name, schema) in properties {
        if let Some(doc) = schema.get("description").and_then(Value::as_str) {
            out.push_str(&comment(doc, &indent));
        }
        let optional = if required.contains(&name.as_str()) {
            ""
        } else {
            "?"
        };
        out.push_str(&format!(
            "{indent}{name}{optional}: {};\n",
            ts_type(schema, depth + 1)
        ));
    }
    out.push_str(&format!("{closing}}}"));
    out
}

fn literal(value: &Value) -> String {
    match value {
        Value::String(text) => format!("\"{text}\""),
        Value::Null => "null".into(),
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(json_schema_document(), json_schema_document());
        assert_eq!(typescript(), typescript());
    }

    /// AC3: every exposed method and notification is in the published document.
    /// The tables the dispatcher uses ARE the tables the schema is built from,
    /// so this asserts the property rather than a copy of it.
    #[test]
    fn the_document_covers_every_exposed_name() {
        let document = json_schema_document();
        let names = |key: &str| -> Vec<String> {
            document
                .get(key)
                .and_then(Value::as_array)
                .map(|entries| {
                    entries
                        .iter()
                        .filter_map(|entry| entry.get("method").and_then(Value::as_str))
                        .map(str::to_string)
                        .collect()
                })
                .unwrap_or_default()
        };
        assert_eq!(names("methods"), CLIENT_METHODS.to_vec());
        assert_eq!(names("notifications"), SERVER_NOTIFICATIONS.to_vec());
        assert_eq!(names("serverRequests"), SERVER_REQUESTS.to_vec());
        // A method entry declares both halves of its contract.
        for entry in document
            .get("methods")
            .and_then(Value::as_array)
            .expect("methods")
        {
            assert!(entry.get("params").is_some());
            assert!(entry.get("result").is_some());
        }
    }

    #[test]
    fn the_typescript_declares_every_method_and_its_types() {
        let ts = typescript();
        for method in CLIENT_METHODS {
            assert!(ts.contains(&format!("\"{method}\":")), "missing {method}");
        }
        for notification in SERVER_NOTIFICATIONS {
            assert!(
                ts.contains(&format!("\"{notification}\":")),
                "missing {notification}"
            );
        }
        assert!(ts.contains("export type ThreadItem ="), "{ts}");
        assert!(ts.contains("export const PROTOCOL_VERSION = 1;"));
        // The flattened correlation is inlined by the derivation: its four
        // identifiers must be readable on the request that carries them.
        let approval = ts
            .split("export type CommandExecutionApprovalParams =")
            .nth(1)
            .and_then(|rest| rest.split("};").next())
            .expect("the approval request is declared");
        for field in ["threadId", "turnId", "itemId", "callId"] {
            assert!(approval.contains(field), "{field} missing from {approval}");
        }
    }
}
