// Generated by `pyxis app-server --emit-schemas`. Do not edit.
// Source of truth: crates/agent-app-server/src/protocol.rs

export const PROTOCOL_VERSION = 1;

/**
 * The four answers a client may give: allow or refuse, once or for the
 * session. Aborting the turn is NOT one of them, because that is
 * `turn/interrupt` and it must reach the model and the tools, not just this
 * one call. A `*ForSession` answer is remembered only when the request said it
 * was memoizable; the pipeline, never the client, decides that.
 */
export type ApprovalDecision = "approved" | "approvedForSession" | "declined" | "declinedForSession";

export type ApprovalDecisionResponse = {
  decision: ApprovalDecision;
};

export type ClientInfo = {
  name: string;
  title?: string | null;
  version?: string | null;
};

export type CommandExecutionApprovalParams = {
  callId: string;
  command: string;
  itemId: string;
  memoRefused?: string | null;
  /**
   * The answer may be remembered for the session.
   */
  memoizable: boolean;
  /**
   * The permission mode in force when the request was raised.
   */
  mode: string;
  reason: string;
  /**
   * The request was forced by recent untrusted content: approving it opts
   * out of the prompt-injection defense for this call.
   */
  taintForced: boolean;
  threadId: string;
  turnId?: string | null;
};

export type DynamicToolCallParams = {
  arguments: unknown;
  callId: string;
  itemId: string;
  threadId: string;
  tool: string;
  turnId?: string | null;
};

export type DynamicToolCallResponse = {
  /**
   * What the model reads. Untrusted like any other tool output.
   */
  content: string;
  isError?: boolean;
  structuredContent?: unknown;
};

/**
 * A tool the client executes on the model's behalf.
 */
export type DynamicToolSpec = {
  description: string;
  inputSchema: unknown;
  name: string;
};

export type EmptyResult = Record<string, unknown>;

export type ErrorNotification = {
  message: string;
  threadId?: string | null;
  turnId?: string | null;
};

export type FileChangeApprovalParams = {
  callId: string;
  /**
   * The tool input, verbatim, so a client can render a real diff.
   */
  input: unknown;
  itemId: string;
  memoRefused?: string | null;
  memoizable: boolean;
  mode: string;
  paths: string[];
  reason: string;
  taintForced: boolean;
  threadId: string;
  tool: string;
  turnId?: string | null;
};

export type InitializeParams = {
  clientInfo: ClientInfo;
  /**
   * Protocol version the client asks for. Absent means "the oldest this
   * build still speaks", never "whatever the server prefers".
   */
  protocolVersion?: number | null;
};

export type InitializeResult = {
  capabilities: ServerCapabilities;
  protocolVersion: number;
  serverInfo: ServerInfo;
};

export type InputItem = {
  text: string;
  type: "text";
};

export type ItemDeltaNotification = {
  delta: string;
  itemId: string;
  threadId: string;
  turnId?: string | null;
};

export type ItemNotification = {
  item: ThreadItem;
  threadId: string;
  turnId?: string | null;
};

export type ItemStatus = "inProgress" | "completed" | "failed";

/**
 * What this build can actually do. Published BEFORE any mutation so a client
 * never discovers a missing capability by having a call fail.
 */
export type ServerCapabilities = {
  /**
   * Client-declared tools may be registered at `thread/start`.
   */
  dynamicTools: boolean;
  /**
   * How many threads this server hosts at once. One, in this build: the tool
   * registry, the Code Mode session and the sub-agent handle of the process
   * each belong to the open thread.
   */
  maxOpenThreads: number;
  maxQueuedBytes: number;
  /**
   * Queue bound past which a slow client is closed (US-018 AC4).
   */
  maxQueuedEvents: number;
  /**
   * Methods served by this build.
   */
  methods: string[];
  /**
   * Notifications this build may push.
   */
  notifications: string[];
  /**
   * Requests this build may send to the client. A client that answers none
   * of them will see every approval fail closed.
   */
  serverRequests: string[];
};

export type ServerInfo = {
  name: string;
  version: string;
};

/**
 * Why a pending server request stopped waiting (US-017 AC3/AC4).
 */
export type ServerRequestResolution = "answered" | "cancelled";

export type ServerRequestResolvedNotification = {
  itemId?: string | null;
  /**
   * The `id` of the server request, as a string whatever its JSON type.
   */
  requestId: string;
  resolution: ServerRequestResolution;
  threadId?: string | null;
  turnId?: string | null;
};

export type ThreadClosedNotification = {
  reason: string;
  threadId: string;
};

/**
 * One projected element of a thread. The same shapes are served by
 * `thread/items/list` and by `item/started` / `item/completed`, so a client
 * writes one renderer.
 */
export type ThreadItem = {
  id: string;
  text: string;
  type: "userMessage";
} | {
  id: string;
  text: string;
  type: "assistantMessage";
} | {
  callId: string;
  command: string;
  exitCode?: number | null;
  id: string;
  output?: string;
  status: ItemStatus;
  type: "commandExecution";
} | {
  callId: string;
  id: string;
  output?: string;
  /**
   * Workspace-relative paths the call declared it would touch.
   */
  paths: string[];
  status: ItemStatus;
  type: "fileChange";
} | {
  callId: string;
  id: string;
  input: unknown;
  output?: string;
  status: ItemStatus;
  tool: string;
  type: "toolCall";
  /**
   * The result carries untrusted content (taint).
   */
  untrusted: boolean;
} | {
  id: string;
  message: string;
  type: "error";
};

export type ThreadItemsListParams = {
  /**
   * Opaque cursor returned by the previous page. Absent starts at the first
   * item.
   */
  cursor?: string | null;
  pageSize?: number | null;
  threadId: string;
};

export type ThreadItemsListResult = {
  items: ThreadItem[];
  /**
   * Absent on the last page.
   */
  nextCursor?: string | null;
};

/**
 * Names a thread. Used on its own as the parameter of `thread/unsubscribe`.
 */
export type ThreadRef = {
  threadId: string;
};

export type ThreadResumeParams = {
  dynamicTools?: DynamicToolSpec[];
  threadId: string;
};

export type ThreadStartParams = {
  /**
   * Tools the CLIENT executes. They enter the same registry, the same
   * permission pipeline and the same dispatch as the built-in ones
   * (US-017 AC2).
   */
  dynamicTools?: DynamicToolSpec[];
};

export type ThreadStartedNotification = {
  threadId: string;
};

export type ThreadStartedResult = {
  /**
   * Items already in the durable log. Read them with `thread/items/list`.
   */
  itemCount: number;
  threadId: string;
};

export type ToolApprovalParams = {
  callId: string;
  input: unknown;
  itemId: string;
  memoRefused?: string | null;
  memoizable: boolean;
  mode: string;
  reason: string;
  summary: string;
  taintForced: boolean;
  threadId: string;
  tool: string;
  turnId?: string | null;
};

export type TurnCompletedNotification = {
  /**
   * Terminal cause, as the durable log recorded it. Present whenever the
   * runtime recorded one, which is what makes a failure diagnosable instead
   * of silent (FR-19).
   */
  cause?: string | null;
  status: TurnStatus;
  threadId: string;
  turnId: string;
};

export type TurnDeltaNotification = {
  delta: string;
  threadId: string;
  turnId?: string | null;
};

export type TurnInterruptParams = {
  threadId: string;
  /**
   * Absent interrupts whatever is running.
   */
  turnId?: string | null;
};

export type TurnStartParams = {
  /**
   * Idempotency key. Two `turn/start` carrying the same key open one turn.
   */
  clientMessageId?: string | null;
  input: InputItem[];
  threadId: string;
};

export type TurnStartedNotification = {
  threadId: string;
  turnId: string;
};

export type TurnStartedResult = {
  threadId: string;
  turnId: string;
};

export type TurnStatus = "completed" | "interrupted" | "failed";

export type TurnSteerParams = {
  clientMessageId?: string | null;
  input: InputItem[];
  threadId: string;
  /**
   * The turn the client believes it is correcting. Naming a turn that is no
   * longer running is refused instead of becoming a new turn.
   */
  turnId?: string | null;
};

export interface ClientRequests {
  "initialize": { params: InitializeParams; result: InitializeResult };
  "thread/start": { params: ThreadStartParams; result: ThreadStartedResult };
  "thread/resume": { params: ThreadResumeParams; result: ThreadStartedResult };
  "thread/unsubscribe": { params: ThreadRef; result: EmptyResult };
  "thread/items/list": { params: ThreadItemsListParams; result: ThreadItemsListResult };
  "turn/start": { params: TurnStartParams; result: TurnStartedResult };
  "turn/steer": { params: TurnSteerParams; result: TurnStartedResult };
  "turn/interrupt": { params: TurnInterruptParams; result: EmptyResult };
}

export interface ServerNotifications {
  "error": { params: ErrorNotification };
  "thread/started": { params: ThreadStartedNotification };
  "thread/closed": { params: ThreadClosedNotification };
  "turn/started": { params: TurnStartedNotification };
  "turn/completed": { params: TurnCompletedNotification };
  "item/started": { params: ItemNotification };
  "item/completed": { params: ItemNotification };
  "item/agentMessage/delta": { params: ItemDeltaNotification };
  "item/commandExecution/outputDelta": { params: ItemDeltaNotification };
  "turn/reasoning/delta": { params: TurnDeltaNotification };
  "serverRequest/resolved": { params: ServerRequestResolvedNotification };
}

export interface ServerRequests {
  "item/commandExecution/requestApproval": { params: CommandExecutionApprovalParams; result: ApprovalDecisionResponse };
  "item/fileChange/requestApproval": { params: FileChangeApprovalParams; result: ApprovalDecisionResponse };
  "item/tool/requestApproval": { params: ToolApprovalParams; result: ApprovalDecisionResponse };
  "item/tool/call": { params: DynamicToolCallParams; result: DynamicToolCallResponse };
}

export type ClientMethod = "initialize" | "thread/start" | "thread/resume" | "thread/unsubscribe" | "thread/items/list" | "turn/start" | "turn/steer" | "turn/interrupt";

export type ServerNotificationMethod = "error" | "thread/started" | "thread/closed" | "turn/started" | "turn/completed" | "item/started" | "item/completed" | "item/agentMessage/delta" | "item/commandExecution/outputDelta" | "turn/reasoning/delta" | "serverRequest/resolved";

export type ServerRequestMethod = "item/commandExecution/requestApproval" | "item/fileChange/requestApproval" | "item/tool/requestApproval" | "item/tool/call";
